### ISSUE TITLE
Restriction of the mode of transport

### ISSUE THREAD

**Issue by lkazarin** [vas3k/home-assistant-berlin-transport#18]
At one of the public transport stop, I would like to see only one view, for example, only buses.

What could I change in this code?

<img width="1052" alt="SCR-20230818-kewy" src="https://github.com/vas3k/home-assistant-berlin-transport/assets/124534184/5ee20819-bc0f-4fe1-a49b-5b56c80ee611">

**Comment by vas3k** [comment]
Right now the component doesn't have a filter function, but you can add one.

For example, like this (open for discussion):

```
filters:
  - type: bus,tram
  - name: M27,N117
```

Next you will need to write code that will take this configuration variable into account and store only the necessary departures. Somewhere here: https://github.com/vas3k/home-assistant-berlin-transport/blob/main/custom_components/berlin_transport/sensor.py#L161

**Comment by lkazarin** [comment]
Thank you, but I'm not a real welder, I just found a mask in the trash :)

**Comment by lkazarin** [comment]
Thank you, but I'm not a real welder, I just found a mask in the trash :)

**Comment by Jellymath** [comment]
I think you can do something like this with existing component:

```yaml
sensor:
  - platform: berlin_transport
    departures:
      - name: "S+U Schönhauser Allee"
        stop_id: 900110001
        bus: true # not really needed as true is default, but added for clarity
        suburban: false
        subway: false
        tram: false
        ferry: false
        express: false
        regional: false
```
