### ISSUE TITLE
Defining how far to look ahead

### ISSUE THREAD

**Issue by StillClueless** [vas3k/home-assistant-berlin-transport#19]
First of all, awesome integration, many thanks. Also, we seem to live in the same neighbourhood. :-D.

So, it says in the documentation:
After fetching the API, it creates one entity for each stop and writes 10 upcoming departures into attributes.departures.

The behaviour is a bit different for me. It seems to show all connections in the upcoming 5 - 10 minutes. Is there a way to define this time span? For instance set it to 20 or thirty minutes?

**Comment by vas3k** [comment]
Hey, neighbor!

Now there is a parameter `walking_time`, which hides all departures with less than N minutes left. Maybe this could help?

```
sensor:
  - platform: berlin_transport
    departures:
      - name: "S+U Schönhauser Allee"
        stop_id: 900110001
        walking_time: 20 # minutes
```
