### ISSUE TITLE
Wrong Lovelac Card

### ISSUE THREAD

**Issue by Bastrim** [vas3k/home-assistant-berlin-transport#20]
Hey together,

thanks for your integration. I follow your steps, but i doesn't got the lovely result.
I do it step by step and got the following result
![Screenshot 2023-10-29 123111](https://github.com/vas3k/home-assistant-berlin-transport/assets/79711510/b2b4396d-1b37-4a92-b58a-9c98dc568eb9)
![Screenshot 2023-10-29 122850](https://github.com/vas3k/home-assistant-berlin-transport/assets/79711510/b1c11cbc-5187-4ab7-8662-90ed6c013e25)

Can you help me? 

I'm new in Home Assistant and i hope to get some support of you.

THX
David

**Comment by vas3k** [comment]
Hey! It looks like your Lovelace dashboard doesn't know this card yet. Did you add `/local/berlin-transport-timetable-card.js` as a dashboard resource here?

<img width="378" alt="Screen 2023-10-29 at 14 06 28" src="https://github.com/vas3k/home-assistant-berlin-transport/assets/176344/0f037ca3-afee-4378-a5ae-8c03d9683b0a">

Try restarting homeassistant after that too. Occasionally it doesn't work the first time.

**Comment by Bastrim** [comment]
Yes Info. Unser www and Like the steps in the description.
![Screenshot_20231029-191301](https://github.com/vas3k/home-assistant-berlin-transport/assets/79711510/48b39ee4-d8f5-4a2c-8c2f-ed5bdfb9018d)

**Comment by Bastrim** [comment]
i tryed to set it per hand and use only the sensor of my stop. Now it works.
![image](https://github.com/vas3k/home-assistant-berlin-transport/assets/79711510/f87dde67-8fd4-4ed4-ac34-221ae2d874d4)
thx for your help

**Comment by Bastrim** [comment]
Maybe one question, can i enter a delay or walktime?

Thx for the help!
David

**Comment by vas3k** [comment]
> i tryed to set it per hand and use only the sensor of my stop. Now it works.

I think the problem was with your sensor name. `sensor.Alt-Marzahn` doesn't seems like a real sensor ID for me. Check your sensors list in `Settings -> Devices and Services -> Entities`


> can i enter a delay or walktime?

Yes, you can. Check the README again

```
sensor:
  - platform: berlin_transport
    departures:
      - name: "S+U Schönhauser Allee"
        stop_id: 900110001
        walking_time: 5 # Optional parameter with value in minutes that hides transport closer than N minutes
```
